STUDENTS = [
    {
        "student_id": 1,
        "name": "Arjun Kumar",
        "email": "arjun@gmail.com",
        "username": "arjun01",
        "course": "Python Full Stack",
        "paid_payment": 30000,
        "total_fee": 50000,
        "last_paid_date": "2025-01-15",
        "pending_amount": 20000,
        "leave_days": 3,
        "attendance": "92%",
        "progress_summary": "Good in Python and backend basics",
        "remarks": "Needs improvement in consistency",
        "course_duration_days": 180,
        "days_completed": 120,
        "mock_interview": [
            {"week_1": "Needs improvement"},
            {"week_2": None},
            {"week_3": "Much improved, needs work on English"}
        ]
    },
    {
        "student_id": 2,
        "name": "Sneha R",
        "email": "sneha@gmail.com",
        "username": "sneha02",
        "course": "MERN Stack",
        "paid_payment": 45000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-01",
        "pending_amount": 15000,
        "leave_days": 1,
        "attendance": "96%",
        "progress_summary": "Strong in React and MongoDB",
        "remarks": "Doing well",
        "course_duration_days": 180,
        "days_completed": 140,
        "mock_interview": [
            {"week_1": "Good understanding"},
            {"week_2": "Improved confidence"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 3,
        "name": "Vishal S",
        "email": "vishal@gmail.com",
        "username": "vishal03",
        "course": "React",
        "paid_payment": 20000,
        "total_fee": 30000,
        "last_paid_date": "2025-01-28",
        "pending_amount": 10000,
        "leave_days": 4,
        "attendance": "88%",
        "progress_summary": "Understands hooks and state",
        "remarks": "Needs practice in projects",
        "course_duration_days": 90,
        "days_completed": 60,
        "mock_interview": [
            {"week_1": "Average"},
            {"week_2": "Improving"},
            {"week_3": "Good"}
        ]
    },
    {
        "student_id": 4,
        "name": "Janani K",
        "email": "janani@gmail.com",
        "username": "janani04",
        "course": "React with Python",
        "paid_payment": 35000,
        "total_fee": 55000,
        "last_paid_date": "2025-02-10",
        "pending_amount": 20000,
        "leave_days": 2,
        "attendance": "94%",
        "progress_summary": "Good in frontend and FastAPI",
        "remarks": "Needs deployment knowledge",
        "course_duration_days": 150,
        "days_completed": 100,
        "mock_interview": [
            {"week_1": "Good"},
            {"week_2": None},
            {"week_3": "Improved backend explanation"}
        ]
    },
    {
        "student_id": 5,
        "name": "Manoj P",
        "email": "manoj@gmail.com",
        "username": "manoj05",
        "course": "Python + Gen AI",
        "paid_payment": 50000,
        "total_fee": 70000,
        "last_paid_date": "2025-02-15",
        "pending_amount": 20000,
        "leave_days": 0,
        "attendance": "98%",
        "progress_summary": "Excellent in LLMs and prompt engineering",
        "remarks": "Top performer",
        "course_duration_days": 120,
        "days_completed": 90,
        "mock_interview": [
            {"week_1": "Excellent"},
            {"week_2": "Very confident"},
            {"week_3": "Industry ready"}
        ]
    },
    {
        "student_id": 6,
        "name": "Abirami T",
        "email": "abirami@gmail.com",
        "username": "abirami06",
        "course": "Python Full Stack",
        "paid_payment": 40000,
        "total_fee": 50000,
        "last_paid_date": "2025-01-20",
        "pending_amount": 10000,
        "leave_days": 2,
        "attendance": "95%",
        "progress_summary": "Strong in Django and REST APIs",
        "remarks": "Needs frontend polish",
        "course_duration_days": 180,
        "days_completed": 150,
        "mock_interview": [
            {"week_1": "Good"},
            {"week_2": "Improved"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 7,
        "name": "Santhosh M",
        "email": "santhosh@gmail.com",
        "username": "santhosh07",
        "course": "Full Stack with Gen AI",
        "paid_payment": 60000,
        "total_fee": 80000,
        "last_paid_date": "2025-02-18",
        "pending_amount": 20000,
        "leave_days": 1,
        "attendance": "97%",
        "progress_summary": "Good in React, FastAPI, and chatbot integration",
        "remarks": "Needs real-time project exposure",
        "course_duration_days": 200,
        "days_completed": 130,
        "mock_interview": [
            {"week_1": "Very good"},
            {"week_2": "Improved"},
            {"week_3": "Needs system design clarity"}
        ]
    },
    {
        "student_id": 8,
        "name": "Thanuj R",
        "email": "thanuj@gmail.com",
        "username": "thanuj08",
        "course": "React",
        "paid_payment": 25000,
        "total_fee": 30000,
        "last_paid_date": "2025-02-05",
        "pending_amount": 5000,
        "leave_days": 3,
        "attendance": "90%",
        "progress_summary": "Understands components and props",
        "remarks": "Needs Redux practice",
        "course_duration_days": 90,
        "days_completed": 55,
        "mock_interview": [
            {"week_1": "Average"},
            {"week_2": "Improved"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 9,
        "name": "Vaikundaraja K",
        "email": "vaiku@gmail.com",
        "username": "vaiku09",
        "course": "MERN Stack",
        "paid_payment": 50000,
        "total_fee": 65000,
        "last_paid_date": "2025-02-12",
        "pending_amount": 15000,
        "leave_days": 2,
        "attendance": "93%",
        "progress_summary": "Good full-stack understanding",
        "remarks": "Needs interview confidence",
        "course_duration_days": 180,
        "days_completed": 110,
        "mock_interview": [
            {"week_1": "Good"},
            {"week_2": "Needs clarity"},
            {"week_3": "Improving"}
        ]
    },
    {
        "student_id": 10,
        "name": "Priya N",
        "email": "priya@gmail.com",
        "username": "priya10",
        "course": "Python and Gen AI",
        "paid_payment": 55000,
        "total_fee": 70000,
        "last_paid_date": "2025-02-20",
        "pending_amount": 15000,
        "leave_days": 0,
        "attendance": "99%",
        "progress_summary": "Strong in embeddings and RAG",
        "remarks": "Ready for client projects",
        "course_duration_days": 120,
        "days_completed": 100,
        "mock_interview": [
            {"week_1": "Excellent"},
            {"week_2": "Industry level"},
            {"week_3": "Very confident"}
        ]
    },

    {
        "student_id": 11,
        "name": "Karthik R",
        "email": "karthik@gmail.com",
        "username": "karthik11",
        "course": "Python Full Stack",
        "paid_payment": 25000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-02",
        "pending_amount": 35000,
        "leave_days": 4,
        "attendance": "89%",
        "progress_summary": "Good in Python basics",
        "remarks": "Needs backend practice",
        "course_duration_days": 180,
        "days_completed": 70,
        "mock_interview": [
            {"week_1": "Average"},
            {"week_2": None},
            {"week_3": "Improving"}
        ]
    },
    {
        "student_id": 12,
        "name": "Divya S",
        "email": "divya@gmail.com",
        "username": "divya12",
        "course": "React",
        "paid_payment": 30000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-08",
        "pending_amount": 30000,
        "leave_days": 2,
        "attendance": "93%",
        "progress_summary": "Strong in hooks",
        "remarks": "Needs Redux",
        "course_duration_days": 90,
        "days_completed": 45,
        "mock_interview": [
            {"week_1": "Good"},
            {"week_2": "Needs confidence"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 13,
        "name": "Rahul M",
        "email": "rahul@gmail.com",
        "username": "rahul13",
        "course": "MERN Stack",
        "paid_payment": 60000,
        "total_fee": 60000,
        "last_paid_date": "2025-01-30",
        "pending_amount": 0,
        "leave_days": 0,
        "attendance": "99%",
        "progress_summary": "Excellent full stack knowledge",
        "remarks": "Placement ready",
        "course_duration_days": 180,
        "days_completed": 160,
        "mock_interview": [
            {"week_1": "Excellent"},
            {"week_2": "Very confident"},
            {"week_3": "Industry ready"}
        ]
    },
    {
        "student_id": 14,
        "name": "Keerthana V",
        "email": "keerthana@gmail.com",
        "username": "keerthana14",
        "course": "Python and Gen AI",
        "paid_payment": 40000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-11",
        "pending_amount": 20000,
        "leave_days": 1,
        "attendance": "96%",
        "progress_summary": "Good in prompt engineering",
        "remarks": "Needs RAG practice",
        "course_duration_days": 120,
        "days_completed": 80,
        "mock_interview": [
            {"week_1": "Good"},
            {"week_2": "Improving"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 15,
        "name": "Naveen K",
        "email": "naveen@gmail.com",
        "username": "naveen15",
        "course": "React with Python",
        "paid_payment": 35000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-14",
        "pending_amount": 25000,
        "leave_days": 3,
        "attendance": "91%",
        "progress_summary": "Good frontend skills",
        "remarks": "Backend needs work",
        "course_duration_days": 150,
        "days_completed": 85,
        "mock_interview": [
            {"week_1": "Average"},
            {"week_2": "Improving"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 16,
        "name": "Pavithra S",
        "email": "pavithra@gmail.com",
        "username": "pavi16",
        "course": "Full Stack with Gen AI",
        "paid_payment": 50000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-16",
        "pending_amount": 10000,
        "leave_days": 1,
        "attendance": "97%",
        "progress_summary": "Good in chatbot APIs",
        "remarks": "Needs deployment exposure",
        "course_duration_days": 200,
        "days_completed": 120,
        "mock_interview": [
            {"week_1": "Good"},
            {"week_2": "Improved"},
            {"week_3": "Needs system design"}
        ]
    },
    {
        "student_id": 17,
        "name": "Ajith P",
        "email": "ajith@gmail.com",
        "username": "ajith17",
        "course": "Python Full Stack",
        "paid_payment": 20000,
        "total_fee": 60000,
        "last_paid_date": "2025-01-25",
        "pending_amount": 40000,
        "leave_days": 5,
        "attendance": "85%",
        "progress_summary": "Basic understanding",
        "remarks": "Needs discipline",
        "course_duration_days": 180,
        "days_completed": 60,
        "mock_interview": [
            {"week_1": "Poor"},
            {"week_2": "Average"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 18,
        "name": "Meena L",
        "email": "meena@gmail.com",
        "username": "meena18",
        "course": "React",
        "paid_payment": 45000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-18",
        "pending_amount": 15000,
        "leave_days": 0,
        "attendance": "98%",
        "progress_summary": "Very strong in UI",
        "remarks": "Project ready",
        "course_duration_days": 90,
        "days_completed": 75,
        "mock_interview": [
            {"week_1": "Very good"},
            {"week_2": "Confident"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 19,
        "name": "Suresh T",
        "email": "suresh@gmail.com",
        "username": "suresh19",
        "course": "MERN Stack",
        "paid_payment": 30000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-06",
        "pending_amount": 30000,
        "leave_days": 2,
        "attendance": "92%",
        "progress_summary": "Understands backend APIs",
        "remarks": "Needs React practice",
        "course_duration_days": 180,
        "days_completed": 90,
        "mock_interview": [
            {"week_1": "Average"},
            {"week_2": "Improving"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 20,
        "name": "Anitha R",
        "email": "anitha@gmail.com",
        "username": "anitha20",
        "course": "Python and Gen AI",
        "paid_payment": 60000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-20",
        "pending_amount": 0,
        "leave_days": 0,
        "attendance": "100%",
        "progress_summary": "Excellent GenAI projects",
        "remarks": "Client-ready",
        "course_duration_days": 120,
        "days_completed": 110,
        "mock_interview": [
            {"week_1": "Excellent"},
            {"week_2": "Outstanding"},
            {"week_3": "Industry ready"}
        ]
    },
    {
        "student_id": 21,
        "name": "Bala K",
        "email": "bala@gmail.com",
        "username": "bala21",
        "course": "React with Python",
        "paid_payment": 28000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-09",
        "pending_amount": 32000,
        "leave_days": 3,
        "attendance": "90%",
        "progress_summary": "Frontend good",
        "remarks": "Needs API integration",
        "course_duration_days": 150,
        "days_completed": 65,
        "mock_interview": [
            {"week_1": "Average"},
            {"week_2": None},
            {"week_3": "Improving"}
        ]
    },
    {
        "student_id": 22,
        "name": "Swetha M",
        "email": "swetha@gmail.com",
        "username": "swetha22",
        "course": "Full Stack with Gen AI",
        "paid_payment": 42000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-17",
        "pending_amount": 18000,
        "leave_days": 1,
        "attendance": "95%",
        "progress_summary": "Good in AI APIs",
        "remarks": "Needs UI polish",
        "course_duration_days": 200,
        "days_completed": 105,
        "mock_interview": [
            {"week_1": "Good"},
            {"week_2": "Improved"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 23,
        "name": "Gokul V",
        "email": "gokul@gmail.com",
        "username": "gokul23",
        "course": "Python Full Stack",
        "paid_payment": 60000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-01",
        "pending_amount": 0,
        "leave_days": 0,
        "attendance": "99%",
        "progress_summary": "Excellent full stack projects",
        "remarks": "Mentor material",
        "course_duration_days": 180,
        "days_completed": 170,
        "mock_interview": [
            {"week_1": "Excellent"},
            {"week_2": "Very confident"},
            {"week_3": "Industry ready"}
        ]
    },
    {
        "student_id": 24,
        "name": "Harini P",
        "email": "harini@gmail.com",
        "username": "harini24",
        "course": "React",
        "paid_payment": 18000,
        "total_fee": 60000,
        "last_paid_date": "2025-01-29",
        "pending_amount": 42000,
        "leave_days": 6,
        "attendance": "82%",
        "progress_summary": "Basics clear",
        "remarks": "Needs serious practice",
        "course_duration_days": 90,
        "days_completed": 40,
        "mock_interview": [
            {"week_1": "Poor"},
            {"week_2": "Average"},
            {"week_3": None}
        ]
    },
    {
        "student_id": 25,
        "name": "Ramesh D",
        "email": "ramesh@gmail.com",
        "username": "ramesh25",
        "course": "MERN Stack",
        "paid_payment": 48000,
        "total_fee": 60000,
        "last_paid_date": "2025-02-19",
        "pending_amount": 12000,
        "leave_days": 1,
        "attendance": "94%",
        "progress_summary": "Good backend and DB",
        "remarks": "Needs frontend speed",
        "course_duration_days": 180,
        "days_completed": 125,
        "mock_interview": [
            {"week_1": "Good"},
            {"week_2": "Improving"},
            {"week_3": None}
        ]
    }
]



